# tools/build_order.py
# =====================================================================
# Topological sort of the concept ledger → generates chapter reading order.
# Output: a list of chapter IDs in dependency order.
# A cycle in the prerequisite graph means a concept is mis-decomposed;
# the script exits with an error and names the cycle.
# =====================================================================

import sys
import heapq
import yaml
from pathlib import Path
from collections import defaultdict


LEDGER_PATH = Path(__file__).parent.parent / "meta" / "ledger.yaml"


def load_ledger(path: Path) -> list[dict]:
    with path.open(encoding="utf-8") as f:
        raw = yaml.safe_load(f)

    if not isinstance(raw, dict):
        raise ValueError(
            f"Ledger root must be a mapping, not {type(raw).__name__}."
        )

    concepts = raw.get("concepts")
    if not isinstance(concepts, list):
        raise ValueError(
            "Ledger must contain a top-level 'concepts' list."
        )

    malformed = [
        index
        for index, item in enumerate(concepts, start=1)
        if not isinstance(item, dict) or not item.get("id")
    ]
    if malformed:
        positions = ", ".join(map(str, malformed))
        raise ValueError(
            f"Concept records at list position(s) {positions} are not "
            "mappings with a non-empty 'id'."
        )

    return concepts


def build_dependency_graph(concepts: list[dict]) -> tuple[dict, dict, dict]:
    """
    Returns:
        id_to_concept : dict mapping concept ID to the concept record
        adj           : dict mapping concept ID to list of concept IDs
                        that depend on it (reverse edges for Kahn's algorithm)
    """
    id_to_concept = {c["id"]: c for c in concepts}
    adj = defaultdict(list)          # id → [dependents]
    in_degree = defaultdict(int)     # id → count of prerequisites

    for concept in concepts:
        cid = concept["id"]
        in_degree.setdefault(cid, 0)
        for prereq in concept.get("prerequisites", []):
            if prereq not in id_to_concept:
                print(
                    f"WARNING: {cid} lists prerequisite '{prereq}' "
                    f"which is not in the ledger.",
                    file=sys.stderr,
                )
                continue
            adj[prereq].append(cid)
            in_degree[cid] += 1

    return id_to_concept, dict(adj), dict(in_degree)


def kahn_sort(
    id_to_concept: dict,
    adj: dict,
    in_degree: dict,
) -> list[str]:
    """
    Kahn's algorithm for topological sort.
    Raises RuntimeError on cycle, naming the concepts involved.
    """
    # Start with all nodes that have no prerequisites
    def priority(cid: str) -> tuple[int, str, str]:
        concept = id_to_concept[cid]
        return (int(concept.get("layer", 99)), str(concept.get("chapter", "99-99")), cid)

    queue = [
        (priority(cid), cid) for cid in id_to_concept
        if in_degree.get(cid, 0) == 0
    ]
    heapq.heapify(queue)
    result = []

    while queue:
        _, cid = heapq.heappop(queue)
        result.append(cid)
        for dependent in sorted(adj.get(cid, [])):
            in_degree[dependent] -= 1
            if in_degree[dependent] == 0:
                heapq.heappush(queue, (priority(dependent), dependent))

    if len(result) != len(id_to_concept):
        cycled = set(id_to_concept) - set(result)
        raise RuntimeError(
            f"CYCLE DETECTED — the following concepts form a dependency "
            f"cycle and cannot be ordered:\n  "
            + "\n  ".join(sorted(cycled))
        )

    return result


def concepts_to_chapter_order(sorted_ids: list[str], id_to_concept: dict) -> list[str]:
    """
    Deduplicate and order chapter IDs based on the first appearance
    of each chapter in the topologically sorted concept list.
    """
    seen = set()
    chapters = []
    for cid in sorted_ids:
        chapter = id_to_concept[cid].get("chapter")
        if chapter and chapter not in seen:
            seen.add(chapter)
            chapters.append(chapter)
    return chapters


def main():
    concepts = load_ledger(LEDGER_PATH)
    print(f"Loaded {len(concepts)} concepts from ledger.", file=sys.stderr)

    id_to_concept, adj, in_degree = build_dependency_graph(concepts)

    try:
        sorted_ids = kahn_sort(id_to_concept, adj, in_degree)
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)

    chapter_order = concepts_to_chapter_order(sorted_ids, id_to_concept)

    print("# Chapter reading order (generated by build_order.py)")
    print("# Do not edit manually — regenerate by running this script.")
    for i, chapter in enumerate(chapter_order, start=1):
        print(f"{i:03d}  {chapter}")

    print(
        f"\n# {len(sorted_ids)} concepts in {len(chapter_order)} chapters. "
        f"No cycles detected.",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
